# Grafana is available at http://localhost:3001/. Login with admin/admin. Configure a Prometheus data source to pull metrics from http://prometheus:9090.

version: "3"
services:
  web:
    build: .
    entrypoint: bin/server
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379/3
    env_file: .dockerenv
    ports:
      - "3000:3000"
    networks:
      - backend
      - monitoring
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  backend:
  monitoring:
