---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: rssbox
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - secretName: rssbox-tls
    hosts:
    - rssbox.example.com       # <-- update hostname
  rules:
  - host: rssbox.example.com   # <-- update hostname
    http:
      paths:
      - path: /
        backend:
          serviceName: rssbox
          servicePort: 3000
